config/routes.rb
Rails.application.routes.draw do

  resources :todos
  root to: "todos#index"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def created                   # <----- START HERE WHEN WORKING ON THE WHOLE ONE-PAGE JAVASCRIPT CLUSTERFUCK
    @todo = Todo.new(todo_params)
    if @todo.save!
      render json: @task, status: :created # <------------------ this simply returns an http status 201 (created) for testing purposes
    else
      render_errors(@todo)
    end
  end

  def show
    @todos = Todo.all
  end

  def update
  end

  def destroy
    todo(params[:id]).destroy
    redirect_to '/'
  end

  private

  def todo_params
    params.require(:todo).permit(:task, :text)
  end

  def todo(todo_id)
    Todo.find(todo_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<div class='fuck_you'>
  <h1>shit list</h1>
  <p>evil things to do<p>

  <%= form_for :todo do |f| %>
    <%= f.text_field :task, placeholder: "add task here", id: "todo-box" %>
  <% end %>

  <br>

  <% @todos.each do |t| %>
    <ul>
      <li> <%= t.task %> </li>
      <%= form_tag(todo_path(t), method: :delete) do %>
        <%= submit_tag 'Destroy' %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>